### ISSUE TITLE
Automate SonarQube Scan

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus#321]
Add a GitHub action for SonarQube scan referring https://github.com/Trimble-Connect/tc-actions/tree/main/sonar-scan-dotnet or https://github.com/SonarSource/sonarqube-scan-action

- [x] trimble-oss/modus-react-bootstrap#181
- [x] trimble-oss/website-modus-bootstrap.trimble.com#219
- [x] trimble-oss/website-modus.trimble.com#244
